package main

import (
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

func main() { //nolint
	cwd, err := os.Getwd()
	if err != nil {
		panic(err)
	}
	out, _ := os.Create("licenses.go")
	_, err = out.Write([]byte("package main \n\n//THIS FILE IS AUTOMATICALLY GENERATED BY `go generate` DO NOT EDIT!\n\nvar licenseString=`"))
	if err != nil {
		panic(err)
	}
	_, err = out.WriteString("LICENSES\n")
	if err != nil {
		panic(err)
	}
	_, err = out.WriteString("========\n")
	if err != nil {
		panic(err)
	}
	defer out.Close()
	err = filepath.Walk(cwd, func(path string, info os.FileInfo, inErr error) error {
		if inErr != nil {
			panic(inErr)
		}
		if strings.HasPrefix("LICENSE", info.Name()) {
			rel, inErr := filepath.Rel(cwd, path)
			if inErr != nil {
				panic(inErr)
			}
			dir := filepath.Dir(rel)
			_, inErr = out.WriteString("FILES: " + dir + "\n")
			if inErr != nil {
				panic(inErr)
			}
			c, inErr := ioutil.ReadFile(path)
			str := string(c)
			str = strings.ReplaceAll(str, "`", "`"+" + \"`\" + `") // escape backticks in license text for go src
			if inErr != nil {
				panic(inErr)
			}
			_, inErr = out.WriteString(str)
			if inErr != nil {
				panic(inErr)
			}
			_, inErr = out.WriteString("\n\n")
			if inErr != nil {
				panic(inErr)
			}

		}
		return nil
	})
	if err != nil {
		panic(err)
	}
	_, err = out.Write([]byte("`\n"))
	if err != nil {
		panic(err)
	}
}
